### ISSUE TITLE
From 4 RPS to 200+ RPS in 90 minutes - Optimizing your Web application

### ISSUE THREAD

**Issue by nmcc** [fullstacklx/talks#1]
In this talk, we will explore several optimizations that can be done to a web application and the database to improve it's throughput and response time.

By using a load generation tool, we'll be able to checkout the result of the several improvements and optimizations as we progress.

**Comment by rogeriopvl** [comment]
@nmcc thanks! can we schedule this talk to April 13th?

**Comment by nmcc** [comment]
Thanks for the feedback, @rogeriopvl.
Sure, go ahead!

**Comment by rogeriopvl** [comment]
Just a note: the meetup has changed to April 6th.
