### ISSUE TITLE
From mobile to consoles, an look at being a solo indie game dev

### ISSUE THREAD

**Issue by DJLink** [fullstacklx/talks#4]
In this talk I will talk about my background as a game developer, particularly as indie and how one game that started as a mobile only made it's way into PC and eventually consoles. 
I will explore some of the things that went good and bad, and a bit about the game tech, frameworks and how that helped (or not) with the porting for the several platforms.

**Comment by rogeriopvl** [comment]
Thanks @DJLink! Scheduled for ~~April 8th~~!

**Comment by rogeriopvl** [comment]
Sorry, I mean April 6th 🤣

**Comment by DJLink** [comment]
Thanks, just double checking April 8th or 6th?  @rogeriopvl

**Comment by DJLink** [comment]
Oh nevermind, got your reply just now. 6th it is :)
